### PR TITLE
fix end date

### PR DESCRIPTION
**Pull request by aadibajpai**
also it's rubik's :)

### CODE REVIEW

**Comment by aadibajpai** [comment]
@gfting sinπ https://www.youtube.com/watch?v=jEI3N9kIyP4

**Review by gfting — APPROVED** [review]
Looks good, nice catches!

**Comment by SamLee514** [comment]
They hired me to copy-paste, not spell check 😤😤😤

**Comment by aadibajpai** [comment]
> They hired me to copy-paste, not spell check 😤😤😤

dw bb they hired me to spell check

**Review by SamLee514 — APPROVED** [review]

**Comment by aadibajpai** [comment]
closing and reopening on non prod branch

**Pull request closed without merging**
